In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
# Baca data dari file CSV
df = pd.read_csv('C:/Users/dfadh/Downloads/hasil__Analisis.csv')

In [3]:
# Mengisi nilai np.nan dengan string kosong ('')
df['Mentions'].fillna('', inplace=True)

In [4]:
df.head()

Pilpres 2024 Unnamed: 1                                         Unnamed: 2  \
0         10000         rt  RT @bachrum_achmadi: Said Iqbal Partai Buruh D...   
1         10001    mention            Banyak sliweran capres cawapres ,,hemm    
2         10002         rt  RT @tvOneNews: Kemarin PSI Bangga Deklarasikan...   
3         10003    mention  Aq pilih âÂ¦@ganjarpranowoâÂ© lah krn di...   
4         10004      reply  @Fahrihamzah Semoga Capres dan Cawapres kali i...   

            Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0  2023-04-28 07:26:12    Twitter   Positive   
1  2023-04-28 07:26:12    Twitter   Positive   
2  2023-04-28 07:26:11    Twitter   Positive   
3  2023-04-28 07:26:08    Twitter   Positive   
4  2023-04-28 07:26:07    Twitter   Positive   

                            Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0        @donnyx17 (donnyx abu hayder)          15         122           0   
1            @oxtutiexx235 (mboketata)         459           0           0   
2    @DadangBudiman14 (Dadang Budiman)          26         122           0   
3  @ichwankalimasad (IchwanKalimasada)        6556           0           0   
4                  @Andi_futago (@lif)          22           0           0   

                                            Mentions  \
0  said iqbal partai buruh dukung ganjar capres pdip   
1               banyak sliweran capres cawapres hemm   
2  kemarin psi bangga deklarasikan ganjar capres ...   
3  aq pilih lah krn dialah yg terbaik dari ketiga...   
4  semoga capres dan cawapres kali ini betul puny...   

                                     Translated_Text Sentiment  
0  Said Iqbal, the Labor Party supports the PDIP ...   positif  
1      lots of presidential cawapres candidates hemm    netral  
2  Yesterday, PSI was proud to declare the reward...   positif  
3  I chose him because he is the best of the thre...   positif  
4  I hope that the presidential and vice presiden...   positif

In [6]:
# Pisahkan teks dan label
texts = df['Mentions'].values
labels = df['Sentiment'].values

In [7]:
# Bagi data menjadi data pelatihan dan data uji
texts_train, texts_test, labels_train, labels_test = train_test_split(texts, labels, test_size=0.2, random_state=42)

In [8]:
# Ubah teks menjadi representasi vektor dengan menggunakan CountVectorizer
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(texts_train)
X_test = vectorizer.transform(texts_test)

In [25]:
# Latih model Naive Bayes
naive_bayes = MultinomialNB(alpha = 0.1)
naive_bayes.fit(X_train, labels_train)

MultinomialNB(alpha=0.1)

In [26]:
# Lakukan prediksi pada data latih dan data uji
predictions_train = naive_bayes.predict(X_train)
predictions_test = naive_bayes.predict(X_test)

In [27]:
# Hitung tingkat akurasi data latih dan data uji
accuracy_train = accuracy_score(labels_train, predictions_train)
accuracy_test = accuracy_score(labels_test, predictions_test)

print(f"Akurasi Data Latih: {accuracy_train * 100:.2f}%")
print(f"Akurasi Data Uji: {accuracy_test * 100:.2f}%")


Akurasi Data Latih: 93.40%
Akurasi Data Uji: 85.40%


In [28]:
# Cetak confusion matrix untuk melihat lebih detail performa model pada data uji
confusion_mat = confusion_matrix(labels_test, predictions_test)
print("Confusion Matrix:")
print(confusion_mat)

Confusion Matrix:
[[ 352   25   70]
 [   9  347  111]
 [  26   51 1009]]
